# Including generated by Boiler. DO NOT EDIT.
include make.mk

# Target section. YOU MAY CHANGE THIS.
.PHONY: help
help:
	boiler --help

.PHONY: generate
generate:
	boiler gen grpc
	boiler gen config
